export const VI = {
  searchPlaceholder: "Tìm kiếm video...",
  filter: "Lọc",
  reset: "Đặt lại",
  apply: "Áp dụng",
  create: "Tạo mới",
  edit: "Sửa",
  delete: "Xóa",
  save: "Lưu",
  cancel: "Hủy",
  confirm: "Xác nhận",
  watchOnYoutube: "Xem trên YouTube",
  close: "Đóng",
  totalVideos: "Tổng số video",
  totalTags: "Tổng số thẻ",
  thisWeek: "Tuần này",
  thisMonth: "Tháng này",
  noResults: "Không có kết quả",
  loading: "Đang tải...",
  error: "Đã xảy ra lỗi",
  success: "Thành công",
  selectVideo: "Chọn một video để xem chi tiết",
  noData: "Chưa có dữ liệu",
  noTags: "Chưa có thẻ nào",
  tagCreated: "Tạo thẻ thành công",
  tagUpdated: "Cập nhật thẻ thành công",
  tagDeleted: "Xóa thẻ thành công",
  tagAttached: "Gán thẻ thành công",
  tagDetached: "Bỏ gán thẻ thành công",
  errorOccurred: "Đã xảy ra lỗi",
  retry: "Thử lại",
  notFoundTitle: "Không tìm thấy nội dung này",
  notFoundDescription: "Trang bạn đang tìm kiếm không tồn tại. Có thể bạn đã nhập sai địa chỉ, hoặc trang đã được di chuyển sang một URL khác. Nếu bạn cho rằng đây là lỗi, vui lòng liên hệ bộ phận hỗ trợ.",
  backToHome: "Quay lại trang chủ",
}
